name: Build Electron (Windows)
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build:win   # atau npx electron-builder --win --x64
      - uses: actions/upload-artifact@v4
        with:
          name: ThinkFlow
          path: dist/*.exe
