name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (tanpa lockfile)
        run: npm install

      - name: Build Windows app
        run: npm run build:win

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ThinkFlow-Windows
          path: dist/
